name: reservas_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  toastification: ^2.3.0
  art_sweetalert: ^0.0.5
  go_router: ^15.1.2
  dartz: ^0.10.1
  package_info_plus: ^8.0.2
  auto_size_text: ^3.0.0
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.4
  logger: ^2.5.0
  equatable: ^2.0.7
  loading_animation_widget: ^1.3.0
  rxdart: ^0.28.0
  google_fonts: ^6.2.1
  
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_inappwebview: ^6.1.5
  pretty_qr_code: ^3.4.0
  fluttertoast: ^8.2.12
  fl_chart: ^1.0.0
  wheel_picker: ^0.2.1
  bottom_picker: ^3.2.0
  pdfx: ^2.9.1
  permission_handler: ^12.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
